spring:
  kafka:
    kafka-server: localhost:9092
    consumer:
      # group-id : consumer 그룹을 식별하는 id로서, 동일한 그룹id를 가진 consumer들은 메세지를 분담해서 consume 함.
      # 만약 여러 consumer가 다른 group-id를 가지고 한 topic을 listen 하면, 각각 메세지를 수신하여 메세지 전파 효과 발생.
      group-id: product-group
      # kafka 내에 들어와 있는 메세지 중 처음 들어온 메세지부터 읽기 시작. (latest : 현 시점 이후 들어오는 메세지만 read)
      auto-offset-reset: earliest